import { ArrowLeft, RotateCcw } from 'lucide-react';
import { AiGuidePlaceholder } from '../components/AiGuidePlaceholder';
import { CategoryScoreCard } from '../components/CategoryScoreCard';
import { RecommendationCard } from '../components/RecommendationCard';
import { ReportButton } from '../components/ReportButton';
import { ScoreCard } from '../components/ScoreCard';
import { useAssessment } from '../context/AssessmentContext';
import { calculateResults } from '../logic/scoring';
export function ResultsPage({onAssessment}:{onAssessment:()=>void}){const {answers,resetAssessment}=useAssessment(); const results=calculateResults(answers); return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm uppercase tracking-[.18em] text-blue-200">Results Dashboard</p><h1 className="mt-2 text-3xl font-bold">Technical safeguard findings</h1><p className="mt-2 text-slate-400">{results.answeredCount}/{results.totalQuestions} verification questions answered.</p></div><div className="flex gap-3"><button onClick={onAssessment} className="inline-flex items-center gap-2 rounded-md border border-slate-700 px-4 py-3 font-semibold"><ArrowLeft className="h-4 w-4"/>Edit answers</button><ReportButton results={results} answers={answers}/></div></div><ScoreCard score={results.overallScore} riskLevel={results.riskLevel}/><AiGuidePlaceholder/><section><h2 className="mb-3 text-xl font-semibold">Category implementation scores</h2><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{results.categoryScores.map(item=><CategoryScoreCard key={item.category} item={item}/>)}</div></section><section><h2 className="mb-3 text-xl font-semibold">Prioritized remediation recommendations</h2><div className="space-y-4">{results.recommendations.length?results.recommendations.map(r=><RecommendationCard key={r.id} recommendation={r}/>):<p className="rounded-lg border border-slate-800 bg-slate-900 p-5 text-slate-300">No weak safeguard categories were detected from the current answers.</p>}</div></section><button onClick={resetAssessment} className="inline-flex items-center gap-2 rounded-md border border-slate-700 px-4 py-3 text-sm font-semibold text-slate-300"><RotateCcw className="h-4 w-4"/>Reset verification</button></div>}
